### ISSUE TITLE
couldn't find "libflutter.so" 怎么破？

### ISSUE THREAD

**Issue by naivor** [jpush/jpush-flutter-plugin#1]
编译出现：

```

  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.turing-AdTojVmR3y7ZMCxsHOc5hA==/base.apk"],nativeLibraryDirectories=[/data/app/com.turing-AdTojVmR3y7ZMCxsHOc5hA==/lib/arm, /data/app/com.turing-AdTojVmR3y7ZMCxsHOc5hA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:163)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:140)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by huangminlinux** [comment]
https://github.com/flutter/flutter/issues/15733

**Comment by naivor** [comment]
my  solution is that:
```
    ndk{
            abiFilters 'arm64-v8a' //'armeabi', 'armeabi-v7a', 'x86', 'x86_64', 'mips', 'mips64'
        }

```

**Comment by fg2q1q3q** [comment]
flutterSDK中找到libflutter.so然后添加到jniLib下对应的文件夹，简单粗暴有效。

**Comment by bobdeng** [comment]
根本原因，是flutter有几种cpu架构他不支持，去掉abiFilters里面不支持的：arm64-v8a，mips64，mips，armeabi就可以了
