### ISSUE TITLE
部分机型报错

### ISSUE THREAD

**Issue by larryluo123** [jpush/jpush-flutter-plugin#129]
HUAWEI荣耀畅玩 6X android 8.0

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.jiguang.jpush.JPushPlugin$JPushReceiver: java.lang.NullPointerException: Attempt to read from field 'java.util.List com.jiguang.jpush.JPushPlugin.getRidCache' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3814)
       at android.app.ActivityThread.-wrap18()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2082)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by raoxudong** [comment]
这只是没做空判断。你上层有什么影响吗？
