### ISSUE TITLE
华为Mate20 App运行过程中导致系统崩溃，是不是没有TRY

### ISSUE THREAD

**Issue by liuhong1happy** [jpush/jpush-flutter-plugin#140]
E/AndroidRuntime( 2843): DeadSystemException: The system died; earlier logs will point to the root cause
W/System.err( 2843): java.lang.RuntimeException: android.os.DeadSystemException
W/System.err( 2843): 	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:1005)
W/System.err( 2843): 	at cn.p.jiguang.d.a.j(Unknown Source:8)
W/System.err( 2843): 	at cn.p.jiguang.cf.a.a(Unknown Source:114)
W/System.err( 2843): 	at cn.p.jiguang.cf.a.a(Unknown Source:27)
W/System.err( 2843): 	at cn.p.jiguang.cf.a.uncaughtException(Unknown Source:22)
W/System.err( 2843): 	at com.loc.aj.uncaughtException(Unknown Source:43)
W/System.err( 2843): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
W/System.err( 2843): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
W/System.err( 2843): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2198)
W/System.err( 2843): Caused by: android.os.DeadSystemException
W/System.err( 2843): 	... 9 more
W/System.err( 2843): java.lang.RuntimeException: android.os.DeadSystemException
W/System.err( 2843): 	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:1005)
W/System.err( 2843): 	at cn.p.jiguang.d.a.j(Unknown Source:8)
W/System.err( 2843): 	at cn.p.jiguang.cf.RC.a(Unknown Source:21)
W/System.err( 2843): 	at cn.p.jiguang.cf.RC.run(Unknown Source:15)
W/System.err( 2843): Caused by: android.os.DeadSystemException
W/System.err( 2843): 	... 4 more
D/JIGUANG-JCommon-P( 2843): [JCommonInterface] onEvent action:deviceinfo

**Comment by qurbanliwayidin** [comment]
这个问题你解决了吗？

**Comment by liuhong1happy** [comment]
> 这个问题你解决了吗？

没有
