### ISSUE TITLE
可以推送消息， 但调用 setTags, getAllTags 等都是Unhandled Exception: PlatformException(6002, , )

### ISSUE THREAD

**Issue by MJJHUA** [jpush/jpush-flutter-plugin#204]
官方demo，和自己对接的app , 都是如此提示。 版本是0.6.0 , 换成0.5.5也是一样提示。。

I/flutter ( 9665): | JPUSH | Flutter | addEventHandler:
I/flutter ( 9665): | JPUSH | Flutter | setup:
I/| JPUSH | Flutter | Android | ( 9665): setup
D/| JPUSH | Flutter | Android | ( 9665): setup :{debug=true, production=false, channel=developer-default, appKey=3d4428f5ca2d683f501f6cce}
D/ActionManager( 9665): addAction type:JPUSH,action:cn.jpush.android.helper.b
D/JIGUANG-JPush( 9665): [JPushInterface] action:init - sdkVersion:3.8.0, buildId:81
D/JIGUANG-JPush( 9665): [AndroidUtil] action:checkValidManifest
I/JIGUANG-JPush( 9665): [JPushConstants] found messageReceiverClass :com.jiguang.jpush.JPushEventReceiverat com.example.projectx by getCommonReceiverNames
D/JIGUANG-JPush( 9665): [AndroidUtil] find authority: com.example.projectx.flutter.image_provider and uri permission is ok
W/JIGUANG-JPush( 9665): [AndroidUtil] AndroidManifest.xml missing apk install required permission, android.permission.REQUEST_INSTALL_PACKAGES
W/JIGUANG-JPush( 9665): [AndroidUtil] You will unable to use install app of in-app message.
D/JIGUANG-JPush( 9665): [ActionHelper] doSingleAction: third_init
D/| JPUSH | Flutter | Android | ( 9665): scheduleCache:
D/JIGUANG-JCore( 9665): [JCoreHelper] runActionWithService action:install_status
D/JIGUANG-JCore( 9665): [JCoreHelper] runActionWithService action:init
I/JIGUANG-JCore( 9665): [JCoreGobal] action:init jcore,version:2.3.4,build id:84,l:234
I/JIGUANG-JCore( 9665): [JCommonServiceHelper] found userServiceClass :com.jiguang.jpush.JPushCustomService by getCommonServiceNames
D/JIGUANG-JPush( 9665): [AndroidUtil] action:checkValidManifest
D/JIGUANG-JCore( 9665): [JCoreHelper] runActionWithService action:get_rid
I/xample.project( 9665): Background concurrent copying GC freed 14915(2MB) AllocSpace objects, 11(220KB) LOS objects, 50% free, 1537KB/3MB, paused 9.286ms total 94.729ms
D/JIGUANG-JPush( 9665): [AndroidUtil] find authority: com.example.projectx.flutter.image_provider and uri permission is ok
W/JIGUANG-JPush( 9665): [AndroidUtil] AndroidManifest.xml missing apk install required permission, android.permission.REQUEST_INSTALL_PACKAGES
D/JIGUANG-JCore( 9665): [JCoreHelper] runActionWithService action:install_status
W/JIGUANG-JPush( 9665): [AndroidUtil] You will unable to use install app of in-app message.
D/| JPUSH | Flutter | Android | ( 9665): runMainThread:map = {isEnabled=true},method =onReceiveNotificationAuthorization
I/flutter ( 9665): | JPUSH | Flutter | _handleMethod:
I/flutter ( 9665): | JPUSH | Flutter | getAllTags:
I/| JPUSH | Flutter | Android | ( 9665): getAllTags
D/| JPUSH | Flutter | Android | ( 9665): getAllTags： 
D/JIGUANG-JCore( 9665): [JCoreHelper] runActionWithService action:tagalis
E/flutter ( 9665): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(6002, , )
E/flutter ( 9665): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter ( 9665): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter ( 9665): <asynchronous suspension>
E/flutter ( 9665): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter ( 9665): #3      JPush.getAllTags (package:jpush_flutter/jpush_flutter.dart:164:24)
E/flutter ( 9665): #4      _MessageContentPage.build.<anonymous closure> (package:projectx/views/message/message_page.dart:37:31)
E/flutter ( 9665): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter ( 9665): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter ( 9665): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter ( 9665): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter ( 9665): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter ( 9665): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
E/flutter ( 9665): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
E/flutter ( 9665): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
E/flutter ( 9665): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
E/flutter ( 9665): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 9665): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
E/flutter ( 9665): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
E/flutter ( 9665): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter ( 9665): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter ( 9665): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter ( 9665): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter ( 9665): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter ( 9665): #22     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 9665): #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 9665): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 9665): #25     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter ( 9665): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
E/flutter ( 9665):

**Comment by MJJHUA** [comment]
[✓] Flutter (Channel stable, 1.19.0-1.0.pre.738, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.19.0-1.0.pre.738 at /Users/DAVID/development/flutter
    • Framework revision 216dee60c0 (6 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/DAVID/Library/Android/sdk
    • Platform android-29, build-tools 30.0.2
    • ANDROID_HOME = /Users/DAVID/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by jcleng** [comment]
flutter升级到1.22试一试,我这边1.22就可以ios就可以接受到消息事件了

**Comment by TinyCXZ** [comment]
不知道对你有没有帮助，有可能是初始化和gettags setalias等方法离得太近，初始化还没有完成。我是在初始化后加了一个延时再执行别的操作。
