### ISSUE TITLE
Android版本崩溃

### ISSUE THREAD

**Issue by xunzzz** [jpush/jpush-flutter-plugin#215]
奔溃日志如下：
Caused by java.lang.IllegalArgumentException: NULL context
       at cn.jpush.android.api.JPushInterface.checkContext(:13)
       at cn.jpush.android.api.JPushInterface.getRegistrationID()
       at com.jiguang.jpush.JPushPlugin.a(JPushPlugin.java:57)
       at com.jiguang.jpush.JPushPlugin.a(JPushPlugin.java:88)
       at com.jiguang.jpush.JPushPlugin$JPushReceiver.onReceive(JPushPlugin.java:5)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4059)
       at android.app.ActivityThread.access$1600(ActivityThread.java:255)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:230)
       at android.app.ActivityThread.main(ActivityThread.java:7778)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

奔溃机型厂商：
![image](https://user-images.githubusercontent.com/13808022/98066759-e3276380-1e92-11eb-92e0-fa00c5e1469e.png)

崩溃机型Android版本：
![image](https://user-images.githubusercontent.com/13808022/98066699-c1c67780-1e92-11eb-89a7-1a413dfed820.png)

**Comment by raoxudong** [comment]
更新0.6.1版本试试
