### ISSUE TITLE
接收后台推送报错版本是最新版

### ISSUE THREAD

**Issue by wozhizhizhi** [jpush/jpush-flutter-plugin#259]
V/SuperLog-native(22340): appendBytesBody byte array
D/JIGUANG-JPush(22340): [JMessageReceiverHelper] not found user push message,use old action to user
D/| JPUSH | Flutter | Android | (22340): handlingMessageReceive cn.jpush.android.intent.MESSAGE_RECEIVED
D/| JPUSH | Flutter | Android | (22340): 
W/Bundle  (22340): Key cn.jpush.android.TYPE_PLATFORM expected String but value was a java.lang.Byte.  The default value <null> was returned.
W/Bundle  (22340): Attempt to cast generated internal exception:
W/Bundle  (22340): java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.String
W/Bundle  (22340): 	at android.os.BaseBundle.getString(BaseBundle.java:1167)
W/Bundle  (22340): 	at android.content.Intent.getStringExtra(Intent.java:8074)
W/Bundle  (22340): 	at com.jiguang.jpush.JPushPlugin$JPushReceiver.getNotificationExtras(JPushPlugin.java:433)
W/Bundle  (22340): 	at com.jiguang.jpush.JPushPlugin$JPushReceiver.handlingMessageReceive(JPushPlugin.java:395)
W/Bundle  (22340): 	at com.jiguang.jpush.JPushPlugin$JPushReceiver.onReceive(JPushPlugin.java:383)
W/Bundle  (22340): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4462)
W/Bundle  (22340): 	at android.app.ActivityThread.access$2700(ActivityThread.java:308)
W/Bundle  (22340): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
W/Bundle  (22340): 	at android.os.Handler.dispatchMessage(Handler.java:110)
W/Bundle  (22340): 	at android.os.Looper.loop(Looper.java:219)
W/Bundle  (22340): 	at android.app.ActivityThread.main(ActivityThread.java:8347)
W/Bundle  (22340): 	at java.lang.reflect.Method.invoke(Native Method)
W/Bundle  (22340): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/Bundle  (22340): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
D/| JPUSH | Flutter | Android | (22340): transmitMessageReceive message=测试华为extras={cn.jpush.android.TYPE_PLATFORM=null, cn.jpush.android.CONTENT_TYPE=text, cn.jpush.android.MSG_ID=54043409349134526, cn.jpush.android.EXTRA={"cur_channel_id":"30005","type":"channel_in"}}
I/flutter (22340): | JPUSH | Flutter | _handleMethod:
I/flutter (22340): flutter onReceiveNotification: {"extras":{"cn.jpush.android.TYPE_PLATFORM":null,"cn.jpush.android.CONTENT_TYPE":"text","cn.jpush.android.MSG_ID":"54043409349134526","cn.jpush.android.EXTRA":"{\"cur_channel_id\":\"30005\",\"type\":\"channel_in\"}"},"message":"测试华为"}

**Comment by xiejibiao** [comment]
紧急求助，我也遇到这个问题了，请问是怎么解决的

**Comment by Moice** [comment]
紧急求助，我也遇到这个问题了，请问是怎么解决的

**Comment by Moice** [comment]
message=111extras={cn.jpush.android.TYPE_PLATFORM=null, cn.jpush.android.CONTENT_TYPE=text, cn.jpush.android.MSG_ID=9007431369107165, cn.jpush.android.EXTRA={"doctorId":"1409714944508694530","msgId":"1417476306464350209","userId":"1417373136009035777"}}
