### ISSUE TITLE
MissingPluginException(No implementation found for method getRegistrationID on channel jpush)#1 JPush.getRegistrationID (package:jpush_flutter/jpush_flutter.dart:381)

### ISSUE THREAD

**Issue by zhanzengyu** [jpush/jpush-flutter-plugin#470]
MissingPluginException(No implementation found for method getRegistrationID on channel jpush)

#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)
<asynchronous suspension>
#1      JPush.getRegistrationID (package:jpush_flutter/jpush_flutter.dart:381)
<asynchronous suspension>

友盟上也捕获到了这个异常，这个是什么情况出现呢？我看源码里面 Android 有实现这个方法。

![image](https://github.com/jpush/jpush-flutter-plugin/assets/17486963/95fae509-5c37-4ee7-bfd7-97ea6a7ab210)

**Comment by atishoo** [comment]
waiting for an answer
