### ISSUE TITLE
设置别名异常，PlatformException(Error 6027, JPush.Flutter, The operation couldn’t be completed. (JPush.Flutter error 6027.), null)

### ISSUE THREAD

**Issue by Doinbe** [jpush/jpush-flutter-plugin#471]
jpush_flutter: 3.0.3，3.0.0，2.5.2这些版本都尝试过，当前是使用的 2.5.2 版本。
flutter: 3.19.5
初始化：
flutter: | JPUSH | Flutter | addEventHandler:
flutter: | JPUSH | Flutter | setup:
| JPUSH | Flutter | iOS | handleMethodCall:setup
| JPUSH | Flutter | iOS | setup:
flutter: | JPUSH | Flutter | applyPushAuthority:
close log collect
 | JIGUANG | I - [JIGUANG] 
--------------------------- JPush Log ----------------------------
--------------------JPush SDK Version:5.2.0--build:382----------
--------------------JCore Lib Version:4.4.0--build:41----------
-----------------AppKey:244c788bfca2914b0f3be4c1----------------
----------------------------------------------------------------
| JPUSH | Flutter | iOS | handleMethodCall:applyPushAuthority
| JPUSH | Flutter | iOS | applyPushAuthority:{
    alert = 1;
    badge = 1;
    sound = 1;
}
| JPUSH | Flutter | iOS |
 | JIGUANG | D - [JIGUANG] Action - registerDeviceToken: {length = 32, bytes = 0xe521af6e 2ceac3a9 d3f19f1a a2a4e477 ... 1fe94f9b f6b4a53b }
 | JIGUANG | W - [JIGUANG] 请将JPush的初始化方法，添加到[UIApplication application: didFinishLaunchingWithOptions:]方法中，否则JPush将不能准确的统计到通知的点击数量。参考文档：https://docs.jiguang.cn/jpush/client/iOS/ios_guide_new/#_6
 | JIGUANG | I - [JIGUANG] Action - closeConection
 | JIGUANG | D - [JIGUANG] +[JPUSHHelper postNotification:withUserInfo:] name: kJPFNetworkIsConnectingNotification (null)
 | JIGUANG | D - [JIGUANG] Action - isSisOnProtect
 | JIGUANG | D - [JIGUANG] sis is not on protect
flutter: | JPUSH | Flutter | _handleMethod:
 | JIGUANG | I - [JIGUANG] Action - jpush setup
 | JIGUANG | D - [JIGUANG] last load config timeinterval: 1719478230472.052, intervals: 86400000, still need: 83899294.373047
 | JIGUANG | D - [JIGUANG] config is invalid , don't start timer
 | JIGUANG | D - [JIGUANG] send udp data
 | JIGUANG | D - [JIGUANG] send udp data succeed
 | JIGUANG | D - [JIGUANG] udp socket begin send behavior
 | JIGUANG | D - [JIGUANG] star Report LocationS trategy
 | JIGUANG | D - [JIGUANG] httpsis, type:active_user, address list:(
    "https://ali-stats.jpush.cn/v3/report",
    "https://stats.jpush.cn/v3/report"
)
 | JIGUANG | D - [JIGUANG] Action - parse
 | JIGUANG | D - [JIGUANG] close udp socket
 | JIGUANG | D - [JIGUANG] 连接主机成功
 | JIGUANG | D - [JIGUANG] JCoreService endConnectionMoniter !!
 | JIGUANG | D - [JIGUANG] +[JPUSHHelper postNotification:withUserInfo:] name: kJPUSHNetworkDidSetupNotification (null)
 | JIGUANG | D - [JIGUANG] Action - doSendTcpRequest
 | JIGUANG | D - [JIGUANG] JCoreService startTcpEventMoniter !!
 | JIGUANG | I - [JIGUANG] 
----- login result -----
uid:75467273458 
registrationID:13165ffa4f034faf771 
idc:1
 | JIGUANG | D - [JIGUANG] +[JPUSHHelper postNotification:withUserInfo:] name: kJPUSHNetworkDidLoginNotification {
    time = 1719480731;
    version = 1;
}
 | JIGUANG | D - [JIGUANG] Action - doSendTcpRequest
 | JIGUANG | I - [JIGUANG] try to upload device token:e521af6e2ceac3a9d3f19f1aa2a4e477d1ea585a6b598b801fe94f9bf6b4a53b
 | JIGUANG | D - [JIGUANG] JCoreService startTcpEventMoniter !!
 | JIGUANG | D - [JIGUANG] JCoreService endConnectionMoniter !!
 | JIGUANG | D - [JIGUANG] JCoreService endHttpMoniter !!
[GETX] Instance "StorageService" has been created
[GETX] Instance "StorageService" has been initialized
[GETX] Instance "PushService" has been created
[GETX] Instance "PushService" has been initialized
[GETX] Instance "ConfigStore" has been created
[GETX] Instance "ConfigStore" has been initialized
[GETX] Instance "UserStore" has been created
[GETX] Instance "UserStore" has been initialized
flutter: BrnLocalizationDelegate load: locale = zh_CN, CN, zh
 | JIGUANG | D - [JIGUANG] JCoreService endHttpMoniter !!
 | JIGUANG | D - [JIGUANG] send report:{
    "app_key" = 244c788bfca2914b0f3be4c1;
    "app_version" = "1.5.14";
    channel = "\U63a8\U9001\U6d88\U606f";
    content =     (
                {
            date = "2024-06-27";
            itime = 1719480731;
            "session_id" = 61bd54f9d6c35348111d38b53a42f00d;
            time = "17:32:11";
            timezone = "+8";
            type = "active_launch";
        }
    );
    "core_sdk_ver" = "4.4.0";
    platform = i;
    "sdk_ver" = "5.2.0";
    "share_sdk_ver" = "";
    "ssp_sdk_ver" = "";
    "statistics_sdk_ver" = "";
    uid = 75467273458;
    "verification_sdk_ver" = "";
} end, result:success
 | JIGUANG | D - [JIGUANG] launchReport 成功
 | JIGUANG | I - [JIGUANG] upload device token success, current token is : e521af6e2ceac3a9d3f19f1aa2a4e477d1ea585a6b598b801fe94f9bf6b4a53b

设置别名的时候就报异常了！

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Error 6027, JPush.Flutter, The operation couldn’t be completed. (JPush.Flutter error 6027.), null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      JPush.setAlias (package:jpush_flutter/jpush_flutter.dart:278:9)
<asynchronous suspension>
#3      JPushHelper.setAlias.<anonymous closure> (package:bimops_fe_app/service/jpush_helper.dart:75:35)
<asynchronous suspension>

**Comment by Doinbe** [comment]
通过 registerid 发送测试消息。是可以正常接收的

**Comment by Doinbe** [comment]
标签/别名设置相关问题（6002、6022、6027等）：https://go48pg.yuque.com/docs/share/b0c4a80d-635d-4f5b-99fd-c9dec8edd038?# 《标签/别名设置相关问题》
