### ISSUE TITLE
分支 dev-3.x 最新提交(更新JPush 540) 导致应用闪退

### ISSUE THREAD

**Issue by naivetoby** [jpush/jpush-flutter-plugin#472]
错误如下

java.lang.IllegalArgumentException: Unsupported value: 'ComponentInfo/com.jiguang.jpush.JPushEventReceiver}' of type 'class android.content.ComponentName'

**Comment by XiaoWei3209** [comment]
me to

**Comment by fdwl** [comment]
me to

**Comment by fdwl** [comment]
现在一启动就直接崩溃了。

**Comment by davidche1116** [comment]
使用jpush_flutter: 3.0.4插件，jpush5.4.0，APP启动后整个界面动画会停止，这时候点击按钮就会闪退。不操作的话，动画卡顿几秒恢复后再操作就不会导致APP闪退。


报错信息如下：
E/CrashReport( 6706): java.lang.IllegalArgumentException: Unsupported value: 'ComponentInfo{com.android.xxx/com.jiguang.jpush.JPushEventReceiver}' of type 'class android.content.ComponentName'
E/CrashReport( 6706): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/CrashReport( 6706): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/CrashReport( 6706): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/CrashReport( 6706): 	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
E/CrashReport( 6706): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:119)
E/CrashReport( 6706): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102)
E/CrashReport( 6706): 	at com.jiguang.jpush.JPushHelper.onCommandResult(JPushHelper.java:170)
E/CrashReport( 6706): 	at com.jiguang.jpush.JPushEventReceiver$1.run(JPushEventReceiver.java:30)
E/CrashReport( 6706): 	at android.os.Handler.handleCallback(Handler.java:1013)
E/CrashReport( 6706): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/CrashReport( 6706): 	at android.os.Looper.loopOnce(Looper.java:226)
E/CrashReport( 6706): 	at android.os.Looper.loop(Looper.java:328)
E/CrashReport( 6706): 	at android.app.ActivityThread.main(ActivityThread.java:9231)
E/CrashReport( 6706): 	at java.lang.reflect.Method.invoke(Native Method)
E/CrashReport( 6706): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
E/CrashReport( 6706): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)


**最新jpush_flutter: 3.0.5修复了这个问题**

**Comment by Deer404** [comment]
jpush_flutter version:3.0.4
crash stack:
): Process: com.sbbaidu.app, PID: 31037
E/AndroidRuntime(31037): java.lang.IllegalArgumentException: Unsupported value: 'ComponentInfo{com.infopeaktechs.app/com.jiguang.jpush.JPushEventReceiver}' of type 'class android.content.ComponentName'
E/AndroidRuntime(31037):        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/AndroidRuntime(31037):        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime(31037):        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime(31037):        at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
E/AndroidRuntime(31037):        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:119)
E/AndroidRuntime(31037):        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102)
E/AndroidRuntime(31037):        at com.jiguang.jpush.JPushHelper.onCommandResult(JPushHelper.java:170)
E/AndroidRuntime(31037):        at com.jiguang.jpush.JPushEventReceiver$1.run(JPushEventReceiver.java:30)
E/AndroidRuntime(31037):        at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(31037):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31037):        at android.os.Looper.loopOnce(Looper.java:257)
E/AndroidRuntime(31037):        at android.os.Looper.loop(Looper.java:368)
E/AndroidRuntime(31037):        at android.app.ActivityThread.main(ActivityThread.java:8848)
E/AndroidRuntime(31037):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31037):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
E/AndroidRuntime(31037):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
D/VRI[MainActivity](31037): dispatchAppVisibility visible:false
