### ISSUE TITLE
flutter 极光推送引起的异常崩溃问题

### ISSUE THREAD

**Issue by MrWangWei** [jpush/jpush-flutter-plugin#485]
D/JIGUANG-JPush( 4006): [JMessageReceiverHelper] not found user push message,use old action to user
D/| JPUSH | Flutter | Android | ( 4006): handlingMessageReceive cn.jpush.android.intent.MESSAGE_RECEIVED
D/| JPUSH | Flutter | Android | ( 4006): transmitMessageReceive message=deviceDataPointUpdateextras={cn.jpush.android.TYPE_PLATFORM=0, cn.jpush.android.CONTENT_TYPE=deviceDataPointUpdate, cn.jpush.android.MSG_ID=18101865603222574, cn.jpush.android.EXTRA={deviceIds=[1862377719451598849]}}
D/AndroidRuntime( 4006): Shutting down VM
I/QarthLog( 4006): [PatchStore] createDisableExceptionQarthFile
I/QarthLog( 4006): [PatchStore] create disable file for tst.com.fyld.aiot_igarden.app uid is 11044
E/AndroidRuntime( 4006): FATAL EXCEPTION: main
E/AndroidRuntime( 4006): Process: tst.com.fyld.aiot_igarden.app, PID: 4006
E/AndroidRuntime( 4006): java.lang.RuntimeException: Unable to start receiver com.jiguang.jpush.JPushPlugin$JPushReceiver: java.lang.IllegalArgumentException: Unsupported value: '[1862377719451598849]' of type 'class org.json.JSONArray'
E/AndroidRuntime( 4006): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4473)
E/AndroidRuntime( 4006): 	at android.app.ActivityThread.access$2700(ActivityThread.java:308)
E/AndroidRuntime( 4006): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
E/AndroidRuntime( 4006): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime( 4006): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime( 4006): 	at android.app.ActivityThread.main(ActivityThread.java:8349)
E/AndroidRuntime( 4006): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4006): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime( 4006): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/AndroidRuntime( 4006): Caused by: java.lang.IllegalArgumentException: Unsupported value: '[1862377719451598849]' of type 'class org.json.JSONArray'
E/AndroidRuntime( 4006): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/AndroidRuntime( 4006): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 4006): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 4006): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 4006): 	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
E/AndroidRuntime( 4006): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:119)
E/AndroidRuntime( 4006): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102)
E/AndroidRuntime( 4006): 	at com.jiguang.jpush.JPushHelper.transmitMessageReceive(JPushHelper.java:144)
E/AndroidRuntime( 4006): 	at com.jiguang.jpush.JPushPlugin$JPushReceiver.handlingMessageReceive(JPushPlugin.java:585)
E/AndroidRuntime( 4006): 	at com.jiguang.jpush.JPushPlugin$JPushReceiver.onReceive(JPushPlugin.java:571)
E/AndroidRuntime( 4006): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4464)

**Comment by cnLiuMing** [comment]
同样的问题
