### ISSUE TITLE
最新版本jpush_flutter: ^3.1.5，启动工程出现闪退，不管是demo工程，还是集成到本地开发工程都会闪退。

### ISSUE THREAD

**Issue by zhang2** [jpush/jpush-flutter-plugin#486]
Launching lib/main.dart on SEA AL10 in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Connecting to VM Service at ws://127.0.0.1:61045/LBT-hrzeg1I=/ws
Connected to the VM Service.
I/flutter ( 2886): | JPUSH | Flutter | addEventHandler:
I/flutter ( 2886): | JPUSH | Flutter | setAuth:
I/flutter ( 2886): | JPUSH | Flutter | setup:
I/| JPUSH | Flutter | Android | ( 2886): setAuth
I/flutter ( 2886): | JPUSH | Flutter | applyPushAuthority:
I/flutter ( 2886): | JPUSH | Flutter | getRegistrationID:
I/flutter ( 2886): | JPUSH | Flutter | pageEnterTo:HomePage
D/ActionManager( 2886): addAction type:JPUSH,action:cn.jpush.android.helper.b
I/| JPUSH | Flutter | Android | ( 2886): setup
D/| JPUSH | Flutter | Android | ( 2886): setup :{debug=true, production=false, channel=theChannel, appKey=xxxxx}
I/JIGUANG-JPush( 2886): [JPushInterface] [key-step]action:init - jpush, SdkVersion:5.5.0, build id:12, build type:release
I/JIGUANG-JCore( 2886): [JCoreGobal] [key-step]main process init - jcore, SdkVersion:4.8.2, build id:35 build type:release
D/JIGUANG-JPush( 2886): [AndroidUtil] action:checkValidManifest
I/JIGUANG-D( 2886): [JDyAndroidUtils] found userServiceClass :com.jiguang.jpush.JPushCustomService by getCommonServiceNames
I/JIGUANG-JPush( 2886): [JPushConstants] found messageServiceClass :com.jiguang.jpush.JPushEventReceiver at com.HuananThirdPush.cn by getComponentInfo
D/JIGUANG-JPush( 2886): [JPushInterface] [key-step]check config suceess!!!
W/JIGUANG-JCore( 2886): [JCoreManager] [register] not same appkey with manifest,please check it
D/JIGUANG-JCore( 2886): [JCoreManager] [key-step][register]  appkey = originKep=xxxxx
D/JIGUANG-JCore( 2886): [JCoreHelper] runActionWithService action:init
D/JIGUANG-JPush( 2886): [ActionHelper] doSingleAction: third_init
D/JIGUANG-JOperate( 2886): [JOperateEventDispatch] onEvent:init,bundle:Bundle[{is_auth=true}]
D/JIGUANG-JPush( 2886): [JPushInterface] setNotificationCallBackEnable
D/JIGUANG-JPush( 2886): [AndroidUtil] action:checkValidManifest
D/JIGUANG-JCore( 2886): [JCoreHelper] runActionWithService action:enable_notification_callback
D/| JPUSH | Flutter | Android | ( 2886): scheduleCache:
D/JIGUANG-JCore( 2886): [JCoreHelper] runActionWithService action:get_rid
D/JIGUANG-JOperate( 2886): [JOperateHelper] init
I/| JPUSH | Flutter | Android | ( 2886): getRegistrationID
D/| JPUSH | Flutter | Android | ( 2886): getRegistrationID:
D/JIGUANG-JCore( 2886): [JCoreHelper] runActionWithService action:get_rid
D/JIGUANG-JOperate( 2886): [JOperateImp] [key-step]try to get operate config
D/JIGUANG-JCore( 2886): [JCoreHelper] runActionWithService action:synce_platform
W/nanThirdPush.c( 2886): Accessing hidden field Landroid/app/ActivityThread;->sCurrentActivityThread:Landroid/app/ActivityThread; (greylist, reflection, allowed)
W/nanThirdPush.c( 2886): Accessing hidden method Landroid/app/ActivityThread;->getApplication()Landroid/app/Application; (greylist, reflection, allowed)
D/JIGUANG-JOperate( 2886): [JOperateEventDispatch] onEvent:start_app,bundle:Bundle[{type=3}]
D/JIGUANG-JCore( 2886): [JCoreHelper] runActionWithService action:notification_state
D/JIGUANG-JCore( 2886): [JCoreHelper] runActionWithService action:sync_target
D/JIGUANG-JCore( 2886): [JCoreHelper] runActionWithService action:handle_cache_message
D/JIGUANG-JCore( 2886): [JCoreHelper] runActionWithService action:change_foreground
D/JIGUANG-JOperate( 2886): [JOperateReport] Current is only jpush,so not allow report
E/nanThirdPush.c( 2886): Invalid ID 0x00000000.
D/JIGUANG-JOperate( 2886): [AndoridUtils] NO versionName defined in manifest.
E/nanThirdPush.c( 2886): Invalid ID 0x00000000.
D/JIGUANG-JOperate( 2886): [AndoridUtils] NO versionName defined in manifest.
E/| JPUSH | Flutter | Android | ( 2886): [onCommandResult] message:CmdMessage{cmd=0, errorCode=10002, msg='Appkey not same with meta appkey', extra=Bundle[{intent_flags=0, intent_component=ComponentInfo{com.HuananThirdPush.cn/com.jiguang.jpush.JPushEventReceiver}, cmd=0, code=10002, intent_action=com.HuananThirdPush.cn.cmd_msg, message=Appkey not same with meta appkey}]}
I/BlockMonitor( 2886): dispatchingThrewException In MainThread
D/AndroidRuntime( 2886): Shutting down VM
I/QarthLog( 2886): [PatchStore] createDisableExceptionQarthFile
I/QarthLog( 2886): [PatchStore] create disable file for com.HuananThirdPush.cn uid is 10267
D/| JPUSH | Flutter | Android | ( 2886): runMainThread:map = {isEnabled=true},method =onReceiveNotificationAuthorization
E/AndroidRuntime( 2886): FATAL EXCEPTION: main
E/AndroidRuntime( 2886): Process: com.HuananThirdPush.cn, PID: 2886
E/AndroidRuntime( 2886): java.lang.IllegalArgumentException: Unsupported value: 'ComponentInfo{com.HuananThirdPush.cn/com.jiguang.jpush.JPushEventReceiver}' of type 'class android.content.ComponentName'
E/AndroidRuntime( 2886): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/AndroidRuntime( 2886): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 2886): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 2886): 	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
E/AndroidRuntime( 2886): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:119)
E/AndroidRuntime( 2886): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102)
E/AndroidRuntime( 2886): 	at com.jiguang.jpush.JPushHelper.onCommandResult(JPushHelper.java:205)
E/AndroidRuntime( 2886): 	at com.jiguang.jpush.JPushEventReceiver$5.run(JPushEventReceiver.java:71)
E/AndroidRuntime( 2886): 	at android.os.Handler.handleCallback(Handler.java:908)
E/AndroidRuntime( 2886): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime( 2886): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime( 2886): 	at android.app.ActivityThread.main(ActivityThread.java:8679)
E/AndroidRuntime( 2886): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2886): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime( 2886): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
D/JIGUANG-JOperate( 2886): [JOperateReport] Current is only jpush,so not allow report
D/NetworkSecurityConfig( 2886): No Network Security Config specified, using platform default
E/nanThirdPush.c( 2886): Invalid ID 0x00000000.
D/JIGUANG-JOperate( 2886): [AndoridUtils] NO versionName defined in manifest.
I/flutter ( 2886): flutter get registration id : 13065ffa4f388258c40
W/Gralloc3( 2886): mapper 3.x is not supported
D/JIGUANG-JCore( 2886): [HttpHelper] status code:200 retry left:2
D/JIGUANG-JPush( 2886): [ActionHelper] doAction:jcore_on_event
E/JIGUANG-JOperate( 2886): [JOperateImp] download e:End of input at character 0 of
I/Process ( 2886): Sending signal. PID: 2886 SIG: 9
Lost connection to device.

Exited.

**Comment by morebuff** [comment]
我真机上也闪退崩溃
java.lang.IllegalArgumentException: Unsupported value: 'ComponentInfo{xxxx.xxxx.app/com.jiguang.jpush.JPushEventReceiver}' of type 'class android.content.ComponentName'
 at n2.s.k(SourceFile:464)
 at n2.s.k(SourceFile:394)
 at n2.s.k(SourceFile:394)
 at n2.t.e(SourceFile:1)
 at n2.i.a(SourceFile:1)
 at z.l.run(SourceFile:129)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.app.ActivityThread.main(ActivityThread.java:8503)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by BIBiBI12** [comment]
Shutting down VM
E/AndroidRuntime( 3696): FATAL EXCEPTION: main
E/AndroidRuntime( 3696): Process: xxxxxx, PID: 3696
E/AndroidRuntime( 3696): java.lang.IllegalArgumentException: Unsupported value: 'ComponentInfo{xxxxxx/com.jiguang.jpush.JPushEventReceiver}' of type 'class android.content.ComponentName'
E/AndroidRuntime( 3696): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/AndroidRuntime( 3696): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 3696): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 3696): 	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
E/AndroidRuntime( 3696): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:119)
E/AndroidRuntime( 3696): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102)
E/AndroidRuntime( 3696): 	at com.jiguang.jpush.JPushHelper.onCommandResult(JPushHelper.java:205)
E/AndroidRuntime( 3696): 	at com.jiguang.jpush.JPushEventReceiver$5.run(JPushEventReceiver.java:71)
E/AndroidRuntime( 3696): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 3696): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3696): 	at android.os.Looper.loopOnce(Looper.java:211)
E/AndroidRuntime( 3696): 	at android.os.Looper.loop(Looper.java:300)
E/AndroidRuntime( 3696): 	at android.app.ActivityThread.main(ActivityThread.java:8503)
E/AndroidRuntime( 3696): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3696): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)

**Comment by zhang2** [comment]
> 我真机上也闪退崩溃 java.lang.IllegalArgumentException: Unsupported value: 'ComponentInfo{xxxx.xxxx.app/com.jiguang.jpush.JPushEventReceiver}' of type 'class android.content.ComponentName' at n2.s.k(SourceFile:464) at n2.s.k(SourceFile:394) at n2.s.k(SourceFile:394) at n2.t.e(SourceFile:1) at n2.i.a(SourceFile:1) at z.l.run(SourceFile:129) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:211) at android.os.Looper.loop(Looper.java:300) at android.app.ActivityThread.main(ActivityThread.java:8503) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

最新3.1.6应该修复了

**Comment by zhang2** [comment]
> Shutting down VM E/AndroidRuntime( 3696): FATAL EXCEPTION: main E/AndroidRuntime( 3696): Process: xxxxxx, PID: 3696 E/AndroidRuntime( 3696): java.lang.IllegalArgumentException: Unsupported value: 'ComponentInfo{xxxxxx/com.jiguang.jpush.JPushEventReceiver}' of type 'class android.content.ComponentName' E/AndroidRuntime( 3696): at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297) E/AndroidRuntime( 3696): at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285) E/AndroidRuntime( 3696): at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285) E/AndroidRuntime( 3696): at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38) E/AndroidRuntime( 3696): at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:119) E/AndroidRuntime( 3696): at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102) E/AndroidRuntime( 3696): at com.jiguang.jpush.JPushHelper.onCommandResult(JPushHelper.java:205) E/AndroidRuntime( 3696): at com.jiguang.jpush.JPushEventReceiver$5.run(JPushEventReceiver.java:71) E/AndroidRuntime( 3696): at android.os.Handler.handleCallback(Handler.java:942) E/AndroidRuntime( 3696): at android.os.Handler.dispatchMessage(Handler.java:99) E/AndroidRuntime( 3696): at android.os.Looper.loopOnce(Looper.java:211) E/AndroidRuntime( 3696): at android.os.Looper.loop(Looper.java:300) E/AndroidRuntime( 3696): at android.app.ActivityThread.main(ActivityThread.java:8503) E/AndroidRuntime( 3696): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime( 3696): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)

最新3.1.6修复了
