### ISSUE TITLE
JPush 在VPN 情况下，网速很慢， 会导致安卓闪退，IOS不会闪退，报错 初始化失败。

### ISSUE THREAD

**Issue by tiancl16** [jpush/jpush-flutter-plugin#49]

**Comment by tiancl16** [comment]
D/JPushPlugin(29170): on get registration
D/JPushPlugin(29170): [io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1@2f995e3, io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1@822be0]
D/AndroidRuntime(29170): Shutting down VM
E/AndroidRuntime(29170): FATAL EXCEPTION: main
E/AndroidRuntime(29170): Process: com.easycloud.LazyCityClient, PID: 29170
E/AndroidRuntime(29170): java.lang.RuntimeException: Unable to start receiver com.jiguang.jpush.JPushPlugin$JPushReceiver: java.util.ConcurrentModificationException
E/AndroidRuntime(29170): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3421)
E/AndroidRuntime(29170): 	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
E/AndroidRuntime(29170): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1684)
E/AndroidRuntime(29170): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29170): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(29170): 	at android.app.ActivityThread.main(ActivityThread.java:6806)
E/AndroidRuntime(29170): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29170): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(29170): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AndroidRuntime(29170): Caused by: java.util.ConcurrentModificationException
E/AndroidRuntime(29170): 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
E/AndroidRuntime(29170): 	at com.jiguang.jpush.JPushPlugin.scheduleCache(JPushPlugin.java:126)
E/AndroidRuntime(29170): 	at com.jiguang.jpush.JPushPlugin.transmitReceiveRegistrationId(JPushPlugin.java:360)
E/AndroidRuntime(29170): 	at com.jiguang.jpush.JPushPlugin$JPushReceiver.onReceive(JPushPlugin.java:255)
E/AndroidRuntime(29170): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3412)
E/AndroidRuntime(29170): 	... 8 more

**Comment by zhangxu123123** [comment]
这个问题解决了吗?第一次安装会造成闪退，之后就可以正常运行

**Comment by nletech** [comment]
我也有这个问题，第一次就会这样

E/AndroidRuntime(13651): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13651): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(13651): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/AndroidRuntime(13651): Caused by: java.util.ConcurrentModificationException
E/AndroidRuntime(13651): 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
E/AndroidRuntime(13651): 	at com.jiguang.jpush.JPushPlugin.scheduleCache(JPushPlugin.java:147)
E/AndroidRuntime(13651): 	at com.jiguang.jpush.JPushPlugin.transmitReceiveRegistrationId(JPushPlugin.java:442)
E/AndroidRuntime(13651): 	at com.jiguang.jpush.JPushPlugin$JPushReceiver.onReceive(JPushPlugin.java:321)
E/AndroidRuntime(13651): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3996)
E/AndroidRuntime(13651): 	... 8 more

**Comment by FakenMaster** [comment]
The developer team never lookup the issues. duplicate #139
