### ISSUE TITLE
run in flutter v1.7.8-hotfix.3 will be crashed

### ISSUE THREAD

**Issue by Torlinone** [jpush/jpush-flutter-plugin#50]
when upgrade flutter to 1.7.8-hotfix.3,run app in debug mode,it will be crash in few seconds.
the log is:
```
10468-10606/com.example.example E/AndroidRuntime: FATAL EXCEPTION: MessageReceiver
    Process: com.example.fireiotmobile, PID: 10468
    java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: MessageReceiver
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
        at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727)
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
        at com.jiguang.jpush.JPushEventReceiver.onAliasOperatorResult(JPushEventReceiver.java:110)
        at cn.jpush.android.a.b.run(Unknown Source:92)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by CaiJingLong** [comment]
```yaml
dependencies:
  jpush_flutter: 
    git: 
      url: https://github.com/CaiJingLong/jpush-flutter-plugin.git
      ref: 4d847f9b2150dc4fd1f8a7620d414d60f464fab7
```

**Comment by Torlinone** [comment]
> ```yaml
> dependencies:
>   jpush_flutter: 
>     git: 
>       url: https://github.com/CaiJingLong/jpush-flutter-plugin.git
>       ref: 4d847f9b2150dc4fd1f8a7620d414d60f464fab7
> ```

大佬回复的速度倒是挺快呢

**Comment by raoxudong** [comment]
可以直接更新最新版本，已修复
